'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText,
  Download,
  Printer,
  X,
  ShieldCheck,
  AlertTriangle,
  ExternalLink,
  Copy,
  Check
} from 'lucide-react';
import { generateInvestigationBrief, formatBriefToMarkdown } from '@/lib/cases/investigation-brief';
import type { InvestigationBrief } from '@/types';

interface InvestigationBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseQuery: string;
}

export default function InvestigationBriefModal({
  isOpen,
  onClose,
  caseQuery
}: InvestigationBriefModalProps) {
  const [brief] = useState<InvestigationBrief>(() => generateInvestigationBrief(caseQuery));
  const [copiedHash, setCopiedHash] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleDownloadMarkdown = () => {
    const md = formatBriefToMarkdown(brief);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `INVESTIGATION-BRIEF-${brief.caseNumber}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const copyHash = (hash: string) => {
    navigator.clipboard.writeText(hash);
    setCopiedHash(hash);
    setTimeout(() => setCopiedHash(null), 2000);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md print:p-0 print:bg-white">
        <motion.div
          initial={{ opacity: 0, scale: 0.96 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.96 }}
          className="w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-[#130B24] border border-purple-500/30 rounded-xl shadow-2xl p-6 text-gray-100 flex flex-col print:border-none print:bg-white print:text-black print:max-h-full"
        >
          {/* Action Bar (Hidden on print) */}
          <div className="flex items-center justify-between pb-4 border-b border-purple-500/20 print:hidden">
            <div className="flex items-center space-x-3">
              <div className="p-2 rounded bg-purple-900/40 text-purple-300">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <span className="text-xs font-mono text-purple-400 font-bold uppercase tracking-wider block">
                  OFFICIAL INVESTIGATION DOSSIER
                </span>
                <h2 className="text-lg font-space font-bold text-white">
                  Case #{brief.caseNumber} — {brief.caseTitle}
                </h2>
              </div>
            </div>

            <div className="flex items-center space-x-2">
              <button
                onClick={handlePrint}
                className="px-3 py-1.5 rounded-lg bg-purple-900/30 hover:bg-purple-900/50 text-purple-300 border border-purple-500/30 text-xs font-semibold flex items-center gap-1.5 transition-colors"
              >
                <Printer className="w-3.5 h-3.5" /> Print
              </button>
              <button
                onClick={handleDownloadMarkdown}
                className="px-3 py-1.5 rounded-lg bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-md transition-all"
              >
                <Download className="w-3.5 h-3.5" /> Download (.md)
              </button>
              <button
                onClick={onClose}
                className="p-1.5 rounded-lg hover:bg-purple-900/40 text-gray-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Dossier Body */}
          <div className="py-6 space-y-6 print:py-2">
            {/* Header Stamp */}
            <div className="border border-purple-500/30 rounded-lg p-4 bg-[#0B0716] flex flex-wrap items-center justify-between gap-4 print:border-gray-400 print:bg-gray-50">
              <div>
                <div className="text-[10px] font-mono text-rose-400 font-bold tracking-widest uppercase">
                  CLASSIFICATION: {brief.classification}
                </div>
                <div className="text-sm font-semibold text-white print:text-black mt-0.5">
                  Generated by: {brief.generatedBy}
                </div>
                <div className="text-xs text-gray-400 print:text-gray-600">
                  Timestamp: {new Date(brief.generatedAt).toLocaleString()}
                </div>
              </div>

              <div className="flex items-center gap-3">
                <div className="text-right">
                  <div className="text-[10px] font-mono text-purple-300 uppercase">PRIORITY INDEX</div>
                  <div className="text-2xl font-bold text-amber-400 print:text-amber-700">
                    {brief.priorityScore.score} <span className="text-xs text-gray-400">/ 100</span>
                  </div>
                </div>
                <div className="p-2 rounded bg-amber-500/10 border border-amber-500/30 text-amber-400 print:text-amber-700">
                  <AlertTriangle className="w-6 h-6" />
                </div>
              </div>
            </div>

            {/* AI Safety Disclaimer */}
            <div className="p-3 rounded-lg bg-amber-950/30 border border-amber-500/30 text-xs text-amber-200/90 print:bg-yellow-50 print:text-yellow-900 print:border-yellow-400">
              <strong>STATUTORY NOTICE:</strong> {brief.priorityScore.disclaimer}
            </div>

            {/* Section 1: Priority Factors */}
            <div>
              <h3 className="text-xs font-mono uppercase tracking-wider text-purple-400 font-bold mb-2">
                1. Contributing Priority & Risk Factors
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {brief.priorityScore.factors.map((f, i) => (
                  <div key={i} className="p-3 rounded-lg bg-[#0B0716] border border-purple-500/20 text-xs print:bg-white print:border-gray-300">
                    <div className="flex items-center justify-between font-semibold text-white print:text-black">
                      <span>{f.factor}</span>
                      <span className="text-purple-400 font-mono">+{f.points} pts</span>
                    </div>
                    <p className="text-gray-400 print:text-gray-600 mt-1">{f.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 2: Primary Subjects */}
            <div>
              <h3 className="text-xs font-mono uppercase tracking-wider text-purple-400 font-bold mb-2">
                2. Primary Subjects of Interest
              </h3>
              <div className="overflow-x-auto rounded-lg border border-purple-500/20">
                <table className="w-full text-left text-xs">
                  <thead className="bg-[#0B0716] text-purple-300 uppercase font-mono print:bg-gray-100 print:text-black">
                    <tr>
                      <th className="p-2.5">ID</th>
                      <th className="p-2.5">Subject Name</th>
                      <th className="p-2.5">Investigative Role</th>
                      <th className="p-2.5 text-center">Degree</th>
                      <th className="p-2.5 text-right">Risk Tier</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-purple-500/10">
                    {brief.primarySubjects.map((s, i) => (
                      <tr key={i} className="hover:bg-purple-950/30">
                        <td className="p-2.5 font-mono text-purple-400">{s.id}</td>
                        <td className="p-2.5 font-bold text-white print:text-black">{s.name}</td>
                        <td className="p-2.5 text-gray-300 print:text-gray-700">{s.role}</td>
                        <td className="p-2.5 text-center font-mono text-white print:text-black">{s.connectionDegree}</td>
                        <td className="p-2.5 text-right font-semibold text-rose-400 print:text-rose-700">{s.riskLevel}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Section 3: Key Evidence */}
            <div>
              <h3 className="text-xs font-mono uppercase tracking-wider text-purple-400 font-bold mb-2">
                3. Key Cryptographic Evidence Register
              </h3>
              <div className="space-y-2">
                {brief.keyEvidence.map((e, i) => (
                  <div key={i} className="p-3 rounded-lg bg-[#0B0716] border border-purple-500/20 text-xs flex flex-col md:flex-row md:items-center justify-between gap-2 print:bg-white print:border-gray-300">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-purple-400 font-bold">{e.id}</span>
                        <span className="px-1.5 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-500/30 text-[10px]">
                          {e.type}
                        </span>
                        <span className="text-emerald-400 flex items-center gap-1 font-semibold text-[11px]">
                          <ShieldCheck className="w-3.5 h-3.5" /> {e.integrityStatus}
                        </span>
                      </div>
                      <p className="text-gray-300 print:text-gray-800 mt-1">{e.description}</p>
                    </div>

                    <div className="flex items-center gap-2 bg-black/40 px-2.5 py-1.5 rounded border border-purple-500/10 font-mono text-[11px] text-gray-300">
                      <span>SHA-256: {e.hash.slice(0, 16)}...</span>
                      <button
                        onClick={() => copyHash(e.hash)}
                        className="hover:text-purple-300 text-gray-500 transition-colors print:hidden"
                      >
                        {copiedHash === e.hash ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 4: AI Recommendations */}
            <div>
              <h3 className="text-xs font-mono uppercase tracking-wider text-purple-400 font-bold mb-2">
                4. Actionable Next Steps & Investigative Inquiries
              </h3>
              <ol className="list-decimal list-inside space-y-1.5 text-xs text-gray-300 print:text-gray-800 bg-[#0B0716] p-3 rounded-lg border border-purple-500/20 print:bg-white print:border-gray-300">
                {brief.aiLeadRecommendations.map((rec, i) => (
                  <li key={i} className="leading-relaxed">{rec}</li>
                ))}
              </ol>
            </div>

            {/* Section 5: Section 65B Notice */}
            <div className="p-3 rounded-lg bg-purple-950/20 border border-purple-500/30 text-[11px] text-purple-200/90 print:bg-gray-100 print:text-black">
              <strong>EVIDENTIARY CHAIN OF CUSTODY (SECTION 65B):</strong> {brief.chainOfCustodyNotice}
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
