import { seedCases, seedPersons, seedEvidence, seedEvents } from '@/data/seed';
import { getCanonicalCaseId, findCanonicalCase } from './case-service';
import { calculateInvestigationPriorityScore } from '@/lib/ai/priority-score';
import { getNodeDegree } from '@/lib/graph/graph-service';
import type { InvestigationBrief } from '@/types';

/**
 * Investigation Brief Generator
 * Generates an executive case dossier for supervisory review, command-level briefing,
 * or judicial submission prep.
 */

export function generateInvestigationBrief(caseQuery: string, generatedBy: string = 'Inspector Priya Sharma'): InvestigationBrief {
  const c = findCanonicalCase(caseQuery) || seedCases[0];
  const priorityScore = calculateInvestigationPriorityScore(c.id);

  // Associated persons
  const primarySubjects = seedPersons
    .filter(p => p.associatedCaseIds.includes(c.id) || p.associatedCaseIds.includes(c.caseNumber))
    .map(p => ({
      id: p.id,
      name: p.name,
      role: p.id === 'P-1042' ? 'Primary Person of Interest (Network Hub)' : 'Associated Co-Subject',
      connectionDegree: getNodeDegree(p.id),
      riskLevel: p.riskLevel
    }));

  // Key evidence
  const keyEvidence = seedEvidence
    .filter(e => e.caseId === c.id)
    .map(e => ({
      id: e.id,
      type: e.type,
      description: e.description,
      hash: e.hash,
      integrityStatus: e.integrityStatus,
      recordedAt: e.createdAt
    }));

  // Cross-case links
  const crossCaseLinks = [
    {
      caseNumber: '2026-017',
      caseTitle: 'Operation Kavach',
      sharedEntity: 'Vehicle MP09-DEMO-4821',
      entityType: 'VEHICLE' as const,
      strength: 94
    },
    {
      caseNumber: '2025-089',
      caseTitle: 'Operation Netra',
      sharedEntity: 'Vehicle RJ-14-CZ-8892',
      entityType: 'VEHICLE' as const,
      strength: 88
    }
  ];

  // Timeline highlights
  const timelineHighlights = seedEvents
    .filter(e => e.caseId === c.id)
    .slice(0, 5)
    .map(e => ({
      id: e.id,
      timestamp: e.timestamp,
      entityId: e.entityId,
      entityType: e.entityType,
      entityName: e.entityName || e.entityId,
      description: e.description,
      source: e.source,
      confidence: e.confidence,
      eventType: 'SURVEILLANCE_CAPTURE'
    }));

  const aiLeadRecommendations = [
    'Execute urgent physical verification of suspect identity card DOC-2026-041-009 with issuing authority.',
    'Issue inter-jurisdictional notification to Indore Crime Branch regarding shared vehicle MP09-DEMO-4821 transit.',
    'Subpoena cell site metadata for identifier ID-DEMO-88421 across Bhopal Central Zone.',
    'Maintain Section 65B compliance for all SHA-256 cryptographic hashes logged in the Evidence Registry.'
  ];

  return {
    caseId: c.id,
    caseNumber: c.caseNumber,
    caseTitle: c.title,
    generatedAt: new Date().toISOString(),
    generatedBy,
    classification: 'LAW ENFORCEMENT SENSITIVE // PROTOTYPE DEMO USE ONLY',
    priorityScore,
    primarySubjects,
    keyEvidence,
    crossCaseLinks,
    timelineHighlights,
    aiLeadRecommendations,
    chainOfCustodyNotice:
      'All cryptographic hashes recorded herein have undergone continuous SHA-256 integrity verification. Digital signatures and audit records are preserved for judicial admissibility under Section 65B of the Indian Evidence Act.'
  };
}

export function formatBriefToMarkdown(brief: InvestigationBrief): string {
  return `# CONFIDENTIAL LAW ENFORCEMENT INVESTIGATION DOSSIER
**CLASSIFICATION:** ${brief.classification}
**GENERATED BY:** ${brief.generatedBy}
**DATE & TIME:** ${new Date(brief.generatedAt).toLocaleString()}
**PRIMARY CASE:** #${brief.caseNumber} — ${brief.caseTitle} (ID: ${brief.caseId})

---

## 1. EXECUTIVE INVESTIGATION PRIORITY
- **Priority Urgency Score:** ${brief.priorityScore.score}/100 [${brief.priorityScore.tier}]
- **Evaluation Tier:** ${brief.priorityScore.label}
- **Statutory AI Safety Notice:** *${brief.priorityScore.disclaimer}*

### Contributing Risk & Urgency Factors:
${brief.priorityScore.factors.map(f => `- **[${f.impact}] ${f.factor} (+${f.points} pts):** ${f.description}`).join('\n')}

---

## 2. PRIMARY SUBJECTS OF INTEREST
| Subject ID | Name | Role / Profile | Network Degree | Risk Tier |
| :--- | :--- | :--- | :--- | :--- |
${brief.primarySubjects.map(s => `| ${s.id} | ${s.name} | ${s.role} | ${s.connectionDegree} connections | ${s.riskLevel || 'HIGH'} |`).join('\n')}

---

## 3. KEY CRYPTOGRAPHIC EVIDENCE
| Evidence ID | Category | Description | SHA-256 Hash | Integrity |
| :--- | :--- | :--- | :--- | :--- |
${brief.keyEvidence.map(e => `| ${e.id} | ${e.type} | ${e.description} | \`${e.hash.slice(0, 16)}...\` | ${e.integrityStatus} |`).join('\n')}

---

## 4. CROSS-JURISDICTIONAL CASE LINKAGES
${brief.crossCaseLinks.map(l => `- **Linked Case #${l.caseNumber} (${l.caseTitle}):** Connected via shared conduit **${l.sharedEntity}** (${l.entityType}) with **${l.strength}% correlation strength**`).join('\n')}

---

## 5. CHRONOLOGICAL INCIDENT HIGHLIGHTS
${brief.timelineHighlights.map(t => `- **${new Date(t.timestamp).toLocaleTimeString()}** — *${t.entityName}*: ${t.description} [Source: ${t.source}, Conf: ${t.confidence}%]`).join('\n')}

---

## 6. AI INVESTIGATIVE RECOMMENDATIONS
${brief.aiLeadRecommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---

## 7. STATUTORY CHAIN OF CUSTODY & DIGITAL INTEGRITY
> ${brief.chainOfCustodyNotice}
`;
}
